services:
  api:
    build: .
    container_name: express_api
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
