services:
  api:
    build: .
    container_name: express_api
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - backend
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - backend

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.1
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
  redis-data:
  rabbitmq-lib:
  rabbitmq-log:
